######################################################################
# Automatically generated by qmake (3.1) Fri Oct 11 13:40:54 2024
######################################################################

TEMPLATE = app
TARGET = Hedgehog
INCLUDEPATH += .

<<<<<<< Updated upstream
QT += core gui qml
# QT += webengine
=======
CONFIG += c++11

QT += core gui qml widgets
QT += webengine
>>>>>>> Stashed changes

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
<<<<<<< Updated upstream
SOURCES += main.cpp
=======
SOURCES += src/main.cpp \
           src/highlighter.cpp \
           src/documenthandler.cpp

HEADERS += includes/highlighter.h \
           includes/documenthandler.h 

>>>>>>> Stashed changes
RESOURCES += resources.qrc